var empId;
empId = 10;
console.log(empId);
console.log(typeof (empId));
empId = 'hiiii';
console.log(empId);
console.log(typeof (empId));
empId = true;
console.log(empId);
console.log(typeof (empId));
